/// Cursor token.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Cursor {
    Auto,
    Default,
    Pointer,
    Wait,
    Text,
    Move,
    Help,
    NotAllowed,
    None,
    ContextMenu,
    Progress,
    Cell,
    Crosshair,
    VerticalText,
    Alias,
    Copy,
    NoDrop,
    Grab,
    Grabbing,
    AllScroll,
    ColResize,
    RowResize,
    NResize,
    EResize,
    SResize,
    WResize,
    NeResize,
    NwResize,
    SeResize,
    SwResize,
    EwResize,
    NsResize,
    NeswResize,
    NwseResize,
    ZoomIn,
    ZoomOut,
}

impl Cursor {
    pub fn value(&self) -> &'static str {
        match self {
            Cursor::Auto => "auto",
            Cursor::Default => "default",
            Cursor::Pointer => "pointer",
            Cursor::Wait => "wait",
            Cursor::Text => "text",
            Cursor::Move => "move",
            Cursor::Help => "help",
            Cursor::NotAllowed => "not-allowed",
            Cursor::None => "none",
            Cursor::ContextMenu => "context-menu",
            Cursor::Progress => "progress",
            Cursor::Cell => "cell",
            Cursor::Crosshair => "crosshair",
            Cursor::VerticalText => "vertical-text",
            Cursor::Alias => "alias",
            Cursor::Copy => "copy",
            Cursor::NoDrop => "no-drop",
            Cursor::Grab => "grab",
            Cursor::Grabbing => "grabbing",
            Cursor::AllScroll => "all-scroll",
            Cursor::ColResize => "col-resize",
            Cursor::RowResize => "row-resize",
            Cursor::NResize => "n-resize",
            Cursor::EResize => "e-resize",
            Cursor::SResize => "s-resize",
            Cursor::WResize => "w-resize",
            Cursor::NeResize => "ne-resize",
            Cursor::NwResize => "nw-resize",
            Cursor::SeResize => "se-resize",
            Cursor::SwResize => "sw-resize",
            Cursor::EwResize => "ew-resize",
            Cursor::NsResize => "ns-resize",
            Cursor::NeswResize => "nesw-resize",
            Cursor::NwseResize => "nwse-resize",
            Cursor::ZoomIn => "zoom-in",
            Cursor::ZoomOut => "zoom-out",
        }
    }
}
